### ISSUE TITLE
Terminated threads at times.[Program can still function]

### ISSUE THREAD

**Issue by Bry-fi** [13o-bbr-bbq/machine_learning_security#19]
This error does not halt the activity of the program. However, during every session I receive this message.
#<Thread:0x00005563295fc8a0@/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:93 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	6: from /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
	5: from /usr/share/metasploit-framework/lib/msf/ui/web/console.rb:72:in `block in initialize'
	4: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:191:in `run'
	3: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:375:in `get_input_line'
	2: from /usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:151:in `pgets'
	1: from /usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:121:in `gets'
/usr/share/metasploit-framework/lib/rex/ui/text/input/buffer.rb:56:in `gets': no implicit conversion of nil into String (TypeError)

**Comment by 13o-bbr-bbq** [comment]
ok, i'll investigate this cause.  
please, just a moment.

**Comment by Bry-fi** [comment]
Understood.
